codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...95"

  status:
    project: yes
    patch: yes
    changes: no
    status:
      patch:
        default:
          threshold: 0.1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "diff"
  behavior: default
  require_changes: no

ignore:
  - "**/*.scala"
