version: '3'
services:
  jscfe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    image: jscdroiddev/narokio-fe
    ports:
      - "80:80"
  jscbe:
    build:
      context: ./be
      dockerfile: Dockerfile
    image: jscdroiddev/narokio-be
    ports:
      - "8080:8080"
