version: '3.1'
services:
  jscfe:
    image: jscdroiddev/narokio-fe:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - jscbe
    volumes:
      - "./assets:/usr/share/nginx/html/assets"
  jscbe:
    image: jscdroiddev/narokio-be:latest
    restart: unless-stopped
    ports:
      - "9001:9001"
    depends_on:
      - jscdb
    volumes:
      - "./conf:/opt/jscbe/conf"
  jscdb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: narokio
      MYSQL_USER: narokio
      MYSQL_PASSWORD: narokio
    volumes:
      - "./db/data:/var/lib/mysql"
    expose:
      - "3306"
