version: 2
jobs:
  typescript_test:
    working_directory: ~/narok
    docker:
      - image: jscdroiddev/jsc-dev-tools:latest
    steps:
      - checkout
      - run:
          name: install
          command: yarn --cwd fe install --silent --no-progress
      - run:
          name: test
          command: yarn --cwd fe --silent run test --coverage
      - run:
          name: codecov
          command: codecov -y ./codecov.yml -f ./fe/coverage/coverage-final.json -F react
  typescript:
    working_directory: ~/narok
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install
          command: yarn --cwd fe install --silent --no-progress
      - run:
          name: build
          command: yarn --cwd fe build:prod --silent --no-progress
  release:
    working_directory: ~/narok
    docker:
      - image: jscdroiddev/jsc-dev-tools:latest
    steps:
      - checkout
      - run:
          name: git-release
          command: |
            ./.circleci/git-release.sh "Latest release of https://narok.io."
workflows:
  version: 2
  do_it_all:
    jobs:
      - typescript_test
      - typescript
      - release:
          requires:
            - typescript
          filters:
            branches:
              only: master
