version: 2
jobs:
  typescript_test:
    working_directory: ~/narok
    docker:
      - image: jscdroiddev/jsc-dev-tools:latest
    steps:
      - checkout
      - run:
          name: Install
          command: yarn --cwd fe install --silent --no-progress
      - run:
          name: Build
          command: yarn --cwd fe build:prod --silent --no-progress
      - run:
          name: Test
          command: yarn --cwd fe --silent run test --coverage
      - run:
          name: Codecov
          command: codecov -y ./codecov.yml -f ./fe/coverage/coverage-final.json -F react
  scala_test:
    working_directory: ~/narok
    docker:
      - image: jscdroiddev/docker-sbt:latest
    steps:
      - checkout
      - run:
          name: Test
          command: cd be && sbt clean coverage test coverageReport
      - run:
          name: Codecov
          command: codecov -y ./codecov.yml -f ./be/target/scala-2.13/coverage-report/cobertura.xml
  release:
    working_directory: ~/narok
    docker:
      - image: jscdroiddev/jsc-dev-tools:latest
    steps:
      - checkout
      - run:
          name: git-release
          command: |
            ./.circleci/git-release.sh "Latest release of https://narok.io."
workflows:
  version: 2
  do_it_all:
    jobs:
      - scala_test
      - typescript_test
      - release:
          requires:
            - typescript_test
            - scala_test
          filters:
            branches:
              only: master
